### ISSUE TITLE
TypeScript paths

### ISSUE THREAD

**Issue by carlocorradini** [joshuajaco/eslint-plugin-workspaces#24]
Enable compatibility with [TypeScript paths](https://www.typescriptlang.org/tsconfig#paths).
Currently, this plugin throws an error when find an import that is listed in `paths`:
```sh
Oops! Something went wrong! :(

ESLint: 8.28.0

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
Occurred while linting [OMITTED]/type-graphql/benchmarks/array/graphql-js/async.ts:1
Rule: "workspaces/no-absolute-imports"
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at relative (node:path:1191:5)
    at isSubPath ([OMITTED]/type-graphql/node_modules/eslint-plugin-workspaces/lib/utils.js:15:24)
    at [OMITTED]/type-graphql/node_modules/eslint-plugin-workspaces/lib/rules/no-absolute-imports.js:31:44
    at Array.forEach (<anonymous>)
    at [OMITTED]/type-graphql/node_modules/eslint-plugin-workspaces/lib/rules/no-absolute-imports.js:30:16
    at ImportDeclaration ([OMITTED]/type-graphql/node_modules/eslint-plugin-workspaces/lib/utils.js:52:7)
    at ruleErrorHandler ([OMITTED]/type-graphql/node_modules/eslint/lib/linter/linter.js:1115:28)
    at [OMITTED]/type-graphql/node_modules/eslint/lib/linter/safe-emitter.js:45:58
ERROR: "check:lint" exited with 2.
```

**Comment by joshuajaco** [comment]
The stacktrace indicates that there seems to be a workspace that does not have a `name` property defined in their `package.json` file. 
In the latest `0.9.0` release these workspaces are ignored.
This should prevent it from crashing. If you however continue to encounter problems feel free to reopen the issue.
